apiVersion: v1
kind: Service
metadata:
  name: {{ template "tempo.gossipRing.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ template "tempo.gossipRing.name" . }}
    {{- include "tempo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: gossip-ring
      port: 7946
      protocol: TCP
      targetPort: http-memberlist
      {{- if .Values.tempo.memberlist.appProtocol }}
      appProtocol: {{ .Values.tempo.memberlist.appProtocol }}
      {{- end }}
  selector:
    {{- include "tempo.gossipRing.selectorLabels" . | nindent 4 }}
